# Generated by Django 6.0.6 on 2026-09-25 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplication',
            name='Aadhaar_Number',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='PAN_Number',
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='aadhaar_document',
            field=models.FileField(blank=True, null=True, upload_to='documents/aadhaar/'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='bank_statement',
            field=models.FileField(blank=True, null=True, upload_to='documents/bank_statement/'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='pan_document',
            field=models.FileField(blank=True, null=True, upload_to='documents/pan/'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='salary_slip',
            field=models.FileField(blank=True, null=True, upload_to='documents/salary_slip/'),
        ),
    ]
