# Generated by Django 6.0.6 on 2026-10-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_auto_20261001_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='aadhaar_document',
            field=models.FileField(blank=True, null=True, upload_to='documents/aadhaar/'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='bank_statement',
            field=models.FileField(blank=True, null=True, upload_to='documents/bank/'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='employment_type',
            field=models.CharField(choices=[('Salaried', 'Salaried'), ('Self-employed', 'Self-employed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='income_proof',
            field=models.FileField(blank=True, null=True, upload_to='documents/income/'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='pan_document',
            field=models.FileField(blank=True, null=True, upload_to='documents/pan/'),
        ),
    ]
